INSERT INTO dbt_source.user_ptnf(BFCID, MLS_NUMBER, USER_SOURCEID, OFFICE_NAME, FNAME, EMAIL, PHONE, MOBILE, USER_CODE, LICENCE_NO, BROKER_TYPE, AGENT_TYPE)
VALUES(%(BFCID)s, %(MLS_NUMBER)s, %(USER_SOURCEID)s, %(OFFICE_NAME)s, %(FNAME)s, %(EMAIL)s, %(PHONE)s, %(MOBILE)s, %(USER_CODE)s, %(LICENCE_NO)s, %(BROKER_TYPE)s, %(AGENT_TYPE)s)
