INSERT INTO dbt_source.property_ptnf (
                        BFCID,MLS_NUMBER, DATASOURCE, UNIT_NUMBER, ADDRESS, CITY, STATE, ZIP, COUNTY, latitude, longitude,TYPE, SUBTYPE, TITLE, DESCRIPTION, PARCEL_NUMBER, BEDS, BATHS, FULLBATHS, HALFBATHS, AREASQFT,
                        LOTSQFT, YEAR_BUILT, DISPLAY_ADDRESS, DISPLAY_LISTING, STATUS, SALEDATE, SALEPRICE,
                        LISTDATE, ORIG_LISTPRICE, CURR_LISTPRICE, DAYS_ON_MARKET, DATE_PRICE_ADJUST, LISTING_URL,
                        VTOUR_URL, MODIF_TIMESTAMP, EXPIRY_DATE, MISC, PHOTO_COUNT, VIDEO_COUNT, PHOTO_MODIF_DATE,
                        VIDEO_MODIF_DATE, DIST_SCHOOL, ELEM_SCHOOL, MIDL_SCHOOL, HIGH_SCHOOL, NABRHD_NAME, NABRHD_DESC,
                        NEARBY_URL, IDENTIFIER, GEOLEVEL, MAIN_PHOTO, PRICE_CHANGE, STATUS_CHANGE, BROKER_CODE,
                        BROKER_NAME, OFFICE_LISTING_YN,GEOM
                    )
                    VALUES (
                        %(BFCID)s,%(MLS_NUMBER)s, %(DATASOURCE)s, %(UNIT_NUMBER)s, %(ADDRESS)s, %(CITY)s, %(STATE)s, %(ZIP)s,
                        %(COUNTY)s, %(latitude)s, %(longitude)s, %(TYPE)s, %(SUBTYPE)s, %(TITLE)s, %(DESCRIPTION)s,
                        %(PARCEL_NUMBER)s, %(BEDS)s, %(BATHS)s, %(FULLBATHS)s, %(HALFBATHS)s, %(AREASQFT)s, %(LOTSQFT)s,
                        %(YEAR_BUILT)s, %(DISPLAY_ADDRESS)s, %(DISPLAY_LISTING)s, %(STATUS)s, %(SALEDATE)s,
                        %(SALEPRICE)s, %(LISTDATE)s, %(ORIG_LISTPRICE)s, %(CURR_LISTPRICE)s, %(DAYS_ON_MARKET)s,
                        %(DATE_PRICE_ADJUST)s, %(LISTING_URL)s, %(VTOUR_URL)s, %(MODIF_TIMESTAMP)s, %(EXPIRY_DATE)s,
                        %(MISC)s, %(PHOTO_COUNT)s, %(VIDEO_COUNT)s, %(PHOTO_MODIF_DATE)s, %(VIDEO_MODIF_DATE)s,
                        %(DIST_SCHOOL)s, %(ELEM_SCHOOL)s, %(MIDL_SCHOOL)s, %(HIGH_SCHOOL)s, %(NABRHD_NAME)s,
                        %(NABRHD_DESC)s, %(NEARBY_URL)s, %(IDENTIFIER)s, %(GEOLEVEL)s, %(MAIN_PHOTO)s,
                        %(PRICE_CHANGE)s, %(STATUS_CHANGE)s, %(BROKER_CODE)s, %(BROKER_NAME)s, %(OFFICE_LISTING_YN)s, st_point(%(longitude)s,%(latitude)s)
                    )
                    ON CONFLICT (BFCID) DO UPDATE
                    SET
                    BFCID = excluded.BFCID,
                    MLS_NUMBER = excluded.MLS_NUMBER,
                    DATASOURCE = excluded.DATASOURCE,
                    UNIT_NUMBER = excluded.UNIT_NUMBER,
                    ADDRESS = excluded.ADDRESS,
                    CITY = excluded.CITY,
                    STATE = excluded.STATE,
                    ZIP = excluded.ZIP,
                    COUNTY = excluded.COUNTY,
                    latitude = excluded.latitude,
                    longitude = excluded.longitude,
                    TYPE = excluded.TYPE,
                    SUBTYPE = excluded.SUBTYPE,
                    TITLE = excluded.TITLE,
                    DESCRIPTION = excluded.DESCRIPTION,
                    PARCEL_NUMBER = excluded.PARCEL_NUMBER,
                    BEDS = excluded.BEDS,
                    BATHS = excluded.BATHS,
                    FULLBATHS = excluded.FULLBATHS,
                    HALFBATHS = excluded.HALFBATHS,
                    AREASQFT = excluded.AREASQFT,
                    LOTSQFT = excluded.LOTSQFT,
                    YEAR_BUILT = excluded.YEAR_BUILT,
                    DISPLAY_ADDRESS = excluded.DISPLAY_ADDRESS,
                    DISPLAY_LISTING = excluded.DISPLAY_LISTING,
                    STATUS = excluded.STATUS,
                    SALEDATE = excluded.SALEDATE,
                    SALEPRICE = excluded.SALEPRICE,
                    LISTDATE = excluded.LISTDATE,
                    ORIG_LISTPRICE = excluded.ORIG_LISTPRICE,
                    CURR_LISTPRICE = excluded.CURR_LISTPRICE,
                    DAYS_ON_MARKET = excluded.DAYS_ON_MARKET,
                    DATE_PRICE_ADJUST = excluded.DATE_PRICE_ADJUST,
                    LISTING_URL = excluded.LISTING_URL,
                    VTOUR_URL = excluded.VTOUR_URL,
                    MODIF_TIMESTAMP = excluded.MODIF_TIMESTAMP,
                    EXPIRY_DATE = excluded.EXPIRY_DATE,
                    MISC = excluded.MISC,
                    PHOTO_COUNT = excluded.PHOTO_COUNT,
                    VIDEO_COUNT = excluded.VIDEO_COUNT,
                    PHOTO_MODIF_DATE = excluded.PHOTO_MODIF_DATE,
                    VIDEO_MODIF_DATE = excluded.VIDEO_MODIF_DATE,
                    DIST_SCHOOL = excluded.DIST_SCHOOL,
                    ELEM_SCHOOL = excluded.ELEM_SCHOOL,
                    MIDL_SCHOOL = excluded.MIDL_SCHOOL,
                    HIGH_SCHOOL = excluded.HIGH_SCHOOL,
                    NABRHD_NAME = excluded.NABRHD_NAME,
                    NABRHD_DESC = excluded.NABRHD_DESC,
                    NEARBY_URL = excluded.NEARBY_URL,
                    IDENTIFIER = excluded.IDENTIFIER,
                    GEOLEVEL = excluded.GEOLEVEL,
                    MAIN_PHOTO = excluded.MAIN_PHOTO,
                    PRICE_CHANGE = excluded.PRICE_CHANGE,
                    STATUS_CHANGE = excluded.STATUS_CHANGE,
                    BROKER_CODE = excluded.BROKER_CODE,
                    BROKER_NAME = excluded.BROKER_NAME,
                    OFFICE_LISTING_YN = excluded.OFFICE_LISTING_YN;
